CREATE TABLE owners
(
    owner_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    CONSTRAINT pk_owners PRIMARY KEY (owner_id)
);

CREATE TABLE pets
(
    pet_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_name VARCHAR(255),
    pet_type VARCHAR(255),
    owner_id INTEGER,
    CONSTRAINT pk_pets PRIMARY KEY (pet_id)
);

-- Required for Spring-Modulith async events
create table event_publication
(
    completion_date  timestamp(6) with time zone,
    publication_date timestamp(6) with time zone,
    id               uuid not null
        primary key,
    event_type       varchar(255),
    listener_id      varchar(255),
    serialized_event varchar(255)
);

